from __future__ import annotations
from lcqpow.LCQPow_py import AlgorithmStatus
from lcqpow.LCQPow_py import LCQProblem
from lcqpow.LCQPow_py import Options
from lcqpow.LCQPow_py import OutputStatistics
from lcqpow.LCQPow_py import PrintLevel
from lcqpow.LCQPow_py import QPSolver
from lcqpow.LCQPow_py import ReturnValue
from lcqpow.LCQPow_py import cscWrapper
from . import LCQPow_py
__all__: list[str] = ['AlgorithmStatus', 'C_STATIONARY_SOLUTION', 'FAILED_SWITCH_TO_DENSE', 'FAILED_SWITCH_TO_SPARSE', 'FAILED_SYM_COMPLEMENTARITY_MATRIX', 'INDEX_OUT_OF_BOUNDS', 'INITIAL_SUBPROBLEM_FAILED', 'INNER_LOOP_ITERATES', 'INVALID_ARGUMENT', 'INVALID_COMPLEMENTARITY_MATRIX', 'INVALID_COMPLEMENTARITY_TOLERANCE', 'INVALID_CONSTRAINT_MATRIX', 'INVALID_ETA_VALUE', 'INVALID_INDEX_ARRAY', 'INVALID_INDEX_POINTER', 'INVALID_INITIAL_PENALTY_VALUE', 'INVALID_LOWER_COMPLEMENTARITY_BOUND', 'INVALID_MAX_ITERATIONS_VALUE', 'INVALID_MAX_RHO_VALUE', 'INVALID_NUMBER_OF_COMP_VARS', 'INVALID_NUMBER_OF_CONSTRAINT_VARS', 'INVALID_NUMBER_OF_OPTIM_VARS', 'INVALID_OBJECTIVE_LINEAR_TERM', 'INVALID_OSQP_BOX_CONSTRAINTS', 'INVALID_PENALTY_UPDATE_VALUE', 'INVALID_PRINT_LEVEL_VALUE', 'INVALID_QPSOLVER', 'INVALID_RHO_OPT', 'INVALID_STATIONARITY_TOLERANCE', 'INVALID_TOTAL_ITER_COUNT', 'INVALID_TOTAL_OUTER_ITER', 'IVALID_SUBPROBLEM_ITER', 'LCQPOBJECT_NOT_SETUP', 'LCQPow_py', 'LCQProblem', 'MAX_ITERATIONS_REACHED', 'MAX_PENALTY_REACHED', 'M_STATIONARY_SOLUTION', 'NONE', 'NOT_YET_IMPLEMENTED', 'OSQP_INITIAL_DUAL_GUESS_FAILED', 'OSQP_INITIAL_PRIMAL_GUESS_FAILED', 'OSQP_SPARSE', 'OSQP_WORKSPACE_NOT_SET_UP', 'OUTER_LOOP_ITERATES', 'Options', 'OutputStatistics', 'PROBLEM_NOT_SOLVED', 'PrintLevel', 'QPOASES_DENSE', 'QPOASES_SPARSE', 'QPSolver', 'ReturnValue', 'SUBPROBLEM_SOLVER_ERROR', 'SUCCESSFUL_RETURN', 'S_STATIONARY_SOLUTION', 'UNABLE_TO_READ_FILE', 'W_STATIONARY_SOLUTION', 'cscWrapper']
C_STATIONARY_SOLUTION: LCQPow_py.AlgorithmStatus  # value = <AlgorithmStatus.C_STATIONARY_SOLUTION: 2>
FAILED_SWITCH_TO_DENSE: LCQPow_py.ReturnValue  # value = <ReturnValue.FAILED_SWITCH_TO_DENSE: 206>
FAILED_SWITCH_TO_SPARSE: LCQPow_py.ReturnValue  # value = <ReturnValue.FAILED_SWITCH_TO_SPARSE: 205>
FAILED_SYM_COMPLEMENTARITY_MATRIX: LCQPow_py.ReturnValue  # value = <ReturnValue.FAILED_SYM_COMPLEMENTARITY_MATRIX: 204>
INDEX_OUT_OF_BOUNDS: LCQPow_py.ReturnValue  # value = <ReturnValue.INDEX_OUT_OF_BOUNDS: 301>
INITIAL_SUBPROBLEM_FAILED: LCQPow_py.ReturnValue  # value = <ReturnValue.INITIAL_SUBPROBLEM_FAILED: 202>
INNER_LOOP_ITERATES: LCQPow_py.PrintLevel  # value = <PrintLevel.INNER_LOOP_ITERATES: 2>
INVALID_ARGUMENT: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_ARGUMENT: 100>
INVALID_COMPLEMENTARITY_MATRIX: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_COMPLEMENTARITY_MATRIX: 118>
INVALID_COMPLEMENTARITY_TOLERANCE: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_COMPLEMENTARITY_TOLERANCE: 102>
INVALID_CONSTRAINT_MATRIX: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_CONSTRAINT_MATRIX: 117>
INVALID_ETA_VALUE: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_ETA_VALUE: 119>
INVALID_INDEX_ARRAY: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_INDEX_ARRAY: 401>
INVALID_INDEX_POINTER: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_INDEX_POINTER: 400>
INVALID_INITIAL_PENALTY_VALUE: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_INITIAL_PENALTY_VALUE: 103>
INVALID_LOWER_COMPLEMENTARITY_BOUND: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_LOWER_COMPLEMENTARITY_BOUND: 120>
INVALID_MAX_ITERATIONS_VALUE: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_MAX_ITERATIONS_VALUE: 104>
INVALID_MAX_RHO_VALUE: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_MAX_RHO_VALUE: 121>
INVALID_NUMBER_OF_COMP_VARS: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_NUMBER_OF_COMP_VARS: 107>
INVALID_NUMBER_OF_CONSTRAINT_VARS: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_NUMBER_OF_CONSTRAINT_VARS: 108>
INVALID_NUMBER_OF_OPTIM_VARS: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_NUMBER_OF_OPTIM_VARS: 106>
INVALID_OBJECTIVE_LINEAR_TERM: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_OBJECTIVE_LINEAR_TERM: 116>
INVALID_OSQP_BOX_CONSTRAINTS: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_OSQP_BOX_CONSTRAINTS: 110>
INVALID_PENALTY_UPDATE_VALUE: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_PENALTY_UPDATE_VALUE: 101>
INVALID_PRINT_LEVEL_VALUE: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_PRINT_LEVEL_VALUE: 115>
INVALID_QPSOLVER: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_QPSOLVER: 109>
INVALID_RHO_OPT: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_RHO_OPT: 114>
INVALID_STATIONARITY_TOLERANCE: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_STATIONARITY_TOLERANCE: 105>
INVALID_TOTAL_ITER_COUNT: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_TOTAL_ITER_COUNT: 111>
INVALID_TOTAL_OUTER_ITER: LCQPow_py.ReturnValue  # value = <ReturnValue.INVALID_TOTAL_OUTER_ITER: 112>
IVALID_SUBPROBLEM_ITER: LCQPow_py.ReturnValue  # value = <ReturnValue.IVALID_SUBPROBLEM_ITER: 113>
LCQPOBJECT_NOT_SETUP: LCQPow_py.ReturnValue  # value = <ReturnValue.LCQPOBJECT_NOT_SETUP: 300>
MAX_ITERATIONS_REACHED: LCQPow_py.ReturnValue  # value = <ReturnValue.MAX_ITERATIONS_REACHED: 200>
MAX_PENALTY_REACHED: LCQPow_py.ReturnValue  # value = <ReturnValue.MAX_PENALTY_REACHED: 201>
M_STATIONARY_SOLUTION: LCQPow_py.AlgorithmStatus  # value = <AlgorithmStatus.M_STATIONARY_SOLUTION: 3>
NONE: LCQPow_py.PrintLevel  # value = <PrintLevel.NONE: 0>
NOT_YET_IMPLEMENTED: LCQPow_py.ReturnValue  # value = <ReturnValue.NOT_YET_IMPLEMENTED: -1>
OSQP_INITIAL_DUAL_GUESS_FAILED: LCQPow_py.ReturnValue  # value = <ReturnValue.OSQP_INITIAL_DUAL_GUESS_FAILED: 209>
OSQP_INITIAL_PRIMAL_GUESS_FAILED: LCQPow_py.ReturnValue  # value = <ReturnValue.OSQP_INITIAL_PRIMAL_GUESS_FAILED: 208>
OSQP_SPARSE: LCQPow_py.QPSolver  # value = <QPSolver.OSQP_SPARSE: 2>
OSQP_WORKSPACE_NOT_SET_UP: LCQPow_py.ReturnValue  # value = <ReturnValue.OSQP_WORKSPACE_NOT_SET_UP: 207>
OUTER_LOOP_ITERATES: LCQPow_py.PrintLevel  # value = <PrintLevel.OUTER_LOOP_ITERATES: 1>
PROBLEM_NOT_SOLVED: LCQPow_py.AlgorithmStatus  # value = <AlgorithmStatus.PROBLEM_NOT_SOLVED: 0>
QPOASES_DENSE: LCQPow_py.QPSolver  # value = <QPSolver.QPOASES_DENSE: 0>
QPOASES_SPARSE: LCQPow_py.QPSolver  # value = <QPSolver.QPOASES_SPARSE: 1>
SUBPROBLEM_SOLVER_ERROR: LCQPow_py.ReturnValue  # value = <ReturnValue.SUBPROBLEM_SOLVER_ERROR: 203>
SUCCESSFUL_RETURN: LCQPow_py.ReturnValue  # value = <ReturnValue.SUCCESSFUL_RETURN: 0>
S_STATIONARY_SOLUTION: LCQPow_py.AlgorithmStatus  # value = <AlgorithmStatus.S_STATIONARY_SOLUTION: 4>
UNABLE_TO_READ_FILE: LCQPow_py.ReturnValue  # value = <ReturnValue.UNABLE_TO_READ_FILE: 302>
W_STATIONARY_SOLUTION: LCQPow_py.AlgorithmStatus  # value = <AlgorithmStatus.W_STATIONARY_SOLUTION: 1>
